name: Gary Goldberg Photography
favicon: null
layout_spectrum: 0.6385315419174731
typography_spectrum: 0.6565555473789573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#606f81'
    - '#e1e4ed'
    - '#333e49'
    - '#aeaeb0'
  brandStrength: 0.875
  lightness: 0.7582666545640677
  saturation: 0.5758404692169279
  rhythmicContrast: 0.5349635649472475
purpose: []
